---
- name: Install epel
  yum:
    name: epel-release
    state: present

- name: SELinux disable
  selinux:
    state: disabled

- name: Nginx install
  yum:
    name: nginx
    state: present