---
- name: VPN
  hosts: all
  gather_facts: true
  become: true

  tasks:
        - name: Install epel-release
            yum:
            name:
                - epel-release
        
        - name: install soft
          yum:
            name:
                - nano
                - traceroute
                - openvpn
                - iperf3
            state: present
            update_cache: true
        
        - name: Disable selinux 
          selinux:
            state: disabled   
