---
- name: AssymetricRouting
  hosts: all
  gather_facts: true
  become: true
  vars_files:
    - /vagrant/defaults/main.yml

  tasks:
# Отключаем запрет ассиметричного роутинга
        - name: set up asynchronous routing
          sysctl:
            name: net.ipv4.conf.all.rp_filter
            value: '0'
            state: present

# Делаем интерфейс enp0s8 в router1 «дорогим»
        - name: set up OSPF
          template:
            src: /vagrant/templates/frr_assym.conf.j2
            dest: /etc/frr/frr.conf
            owner: frr
            group: frr
            mode: 0640
        
# Перезапускам FRR 
        - name: restart FRR
          service:
            name: frr
            state: restarted
            enabled: true
