---
- name: OSPF
  hosts: all
  gather_facts: true
  become: true
  vars_files:
    - /vagrant/defaults/main.yml

  tasks:
        - name: install soft
          apt:
            name:
                - nano
                - traceroute
                - tcpdump
                - net-tools
            state: present
            update_cache: true

# Отключаем UFW и удаляем его из автозагрузки
        - name: disable ufw service
          service:
            name: ufw 
            state: stopped
            enabled: false

# Добавляем gpg-key репозитория
        - name: add gpg frrouting.org
          apt_key:
            url: "https://deb.frrouting.org/frr/keys.asc"
            state: present

# Добавляем репозиторий https://deb.frrouting.org/frr
        - name: add frr repo
          apt_repository:
            repo: 'deb https://deb.frrouting.org/frr {{ ansible_distribution_release }} frr-stable'
            state: present

# Обновляем пакеты и устанавливаем FRR
        - name: install FRR packages
          apt:
            name:
              - frr
              - frr-pythontools
            state: present
            update_cache: true

# Включаем маршрутизацию транзитных пакетов
        - name: set up forward packages across routers
          sysctl:
            name: net.ipv4.conf.all.forwarding
            value: '1'
            state: present

# Копируем файл daemons на хосты, указываем владельца и права
        - name: base set up OSPF
          template:
            src: /vagrant/templates/daemons  
            dest: /etc/frr/daemons
            owner: frr
            group: frr
            mode: 0640

# Копируем файл frr.conf на хосты, указываем владельца и права
        - name: set up OSPF
          template:
            src: /vagrant/templates/frr.conf.j2
            dest: /etc/frr/frr.conf
            owner: frr
            group: frr
            mode: 0640

# Перезапускам FRR и добавляем в автозагрузку
        - name: restart FRR
          service:
            name: frr
            state: restarted
            enabled: true
