# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  
  config.vm.box = "centos/8.4"
		
		
#		config.vm.provider "virtualbox" do | systemd |
		
			
		


		end
		 
#end
