# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
config.vm.define "server" do |server|
  server.vm.hostname = "server.loc"
  server.vm.network "private_network", ip: "192.168.10.10"
  server.vm.provision "shell", run: "always", path: "ssh_password_on.sh"
end
  
config.vm.define "client" do |client|
  client.vm.hostname = "client.loc"
  client.vm.network "private_network", ip: "192.168.10.20"
  client.vm.provision "shell", run: "always", path: "ssh_password_on.sh"
end

config.vm.define "ansible" do |ansible|
  ansible.vm.hostname = "ansible"
  ansible.vm.network "private_network", ip: "192.168.10.30"
  ansible.vm.provision "shell", run: "always", path: "ansible_install.sh"
end

end