# -*- mode: ruby -*-
# vi: set ft=ruby :
#sudo parted /dev/sdb -s mklabel gpt
#sudo parted /dev/sdc -s mklabel gpt
#sudo parted /dev/sdd -s mklabel gpt
#sudo parted /dev/sde -s mklabel gpt
#sudo parted /dev/sdf -s mklabel gpt


# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
$script = <<-'SCRIPT'
sudo yum install mdadm -y && yes | sudo mdadm --create /dev/md/raid6 --level=6  --raid-devices=5 /dev/sd[b-f] && sudo mkfs.ext4 /dev/md/raid6 && sudo mkdir /raid && sudo mount /dev/md/raid6 /raid && sudo sh -c 'echo "/dev/md/raid6 /raid ext4 defaults">>/etc/fstab'
SCRIPT



Vagrant.configure("2") do |config|
	config.vm.box = "centos/8"
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
	
		config.vm.provider "virtualbox" do | v |
			v.customize ["createhd",  "--filename", "machine1_disk0", "--size", "4096"]
			v.customize ["createhd",  "--filename", "machine1_disk1", "--size", "4096"]
			v.customize ["createhd",  "--filename", "machine1_disk2", "--size", "4096"]
			v.customize ["createhd",  "--filename", "machine1_disk3", "--size", "4096"]
			v.customize ["createhd",  "--filename", "machine1_disk4", "--size", "4096"]
			v.customize ["storagectl", :id, "--name", "SATA Controller", "--add", "sata"]
			v.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", "1", "--type", "hdd", "--medium", "machine1_disk0.vdi"]
			v.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", "2", "--type", "hdd", "--medium", "machine1_disk1.vdi"]
			v.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", "3", "--type", "hdd", "--medium", "machine1_disk2.vdi"]
			v.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", "4", "--type", "hdd", "--medium", "machine1_disk3.vdi"]
			v.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", "5", "--type", "hdd", "--medium", "machine1_disk4.vdi"]
		
		
	
		config.vm.provision "shell", 
			inline: $script
		end	
	
		
		
	end
	  



  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL