---
- hosts: all
  gather_facts: true
  become: true

  tasks:

# echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
    - name: disable default route
      lineinfile:
        dest: /etc/sysconfig/network-scripts/ifcfg-eth0
        line: DEFROUTE=no
      when: (ansible_hostname == "centralRouter") or
            (ansible_hostname == "centralServer")

# echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
    - name: add default gateway for centralRouter
      lineinfile:
        dest: /etc/sysconfig/network-scripts/ifcfg-eth1
        line: GATEWAY=192.168.255.1
      when: (ansible_hostname == "centralRouter")

# echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
    - name: add default gateway for centralServer
      lineinfile:
        dest: /etc/sysconfig/network-scripts/ifcfg-eth1
        line: GATEWAY=192.168.0.1
      when: (ansible_hostname == "centralServer")
