
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
	config.vm.box = "centos/7"
	config.vm.box_version = "2004.01"

	config.vm.provider "virtualbox" do |v|
	v.memory = 512
	v.cpus = 1
	end
	
	
	config.vm.define "web" do |web|
		web.vm.network "private_network", ip: "192.168.50.10",
		virtualbox__intnet: "net1"
		web.vm.hostname = "web"
#		a_host.ssh.username = 'vagrant'
#		a_host.ssh.password = 'vagrant'
#  		a_host.ssh.keys_only = false
		web.vm.provision "shell", inline: <<-SHELL
		sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config    
		systemctl restart sshd.service
		SHELL

	end


	config.vm.define "log" do |log|
		log.vm.network "private_network", ip: "192.168.50.11",
		virtualbox__intnet: "net1"
		log.vm.hostname = "log"
#		config.ssh.username = 'vagrant'
# 		config.ssh.password = 'vagrant'
# 		config.ssh.keys_only = false
        log.vm.provision "shell", inline: <<-SHELL
		sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config    
		systemctl restart sshd.service
		SHELL
	end

    config.vm.define "elk" do |elk|
		elk.vm.network "private_network", ip: "192.168.50.10",
		virtualbox__intnet: "net1"
		elk.vm.hostname = "elk"
#		a_host.ssh.username = 'vagrant'
#		a_host.ssh.password = 'vagrant'
#  		a_host.ssh.keys_only = false
        elk.vm.provision "shell", inline: <<-SHELL
		sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config    
		systemctl restart sshd.service
		SHELL

	end

end    