---
- name: Install packages
  yum:
    name: 
      - gcc
      - python-pip
      - python-devel
      - django
    state: present

- name: pip install setuptools
  pip:
    name: setuptools

- name: pip install django
  pip:
    name: Django

- name: pip install uwsgi
  pip:
    name: uwsgi

- name: Add django user
  user:
    name: django
    group: nginx
    shell: /bin/bash
    home: /var/www/django
    system: yes

- name: Django directory
  file:
    path: /var/www/django
    state: directory
    mode: '0770'
    owner: django
    group: nginx

- name: Django project
  shell: |
    cd /var/www/django 
    django-admin startproject homework
    cd /var/www/django/homework
    python manage.py migrate
  become_user: django

- name: Allow connect to django
  lineinfile:
    path: /var/www/django/homework/homework/settings.py
    regexp: '^ALLOWED_HOSTS'
    line: "ALLOWED_HOSTS = ['localhost']"
  become_user: django

- name: Uwsgi directory
  file:
    path: /etc/uwsgi/sites
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Uwsgi config
  copy: 
    src: homework.ini 
    dest: /etc/uwsgi/sites/homework.ini

- name: Uwsgi systemd
  copy: 
    src: uwsgi.service 
    dest: /etc/systemd/system/uwsgi.service

- name: Uwsgi restart
  systemd:
    name: uwsgi
    state: restarted
    daemon-reload: yes
    enabled: yes

- name: Uwsgi config for nginx
  copy: 
    src: uwsgi.conf 
    dest: /etc/nginx/conf.d/uwsgi.conf

- name: Nginx restart
  systemd:
    name: nginx
    state: restarted
    enabled: yes