# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
	config.vm.box = "centos/8"
	config.vm.box_version = "2011.0"

	config.vm.provider "virtualbox" do |v|
	v.memory = 256
	v.cpus = 1
	end
	
	
	config.vm.define "server" do |server|
		server.vm.network "private_network", ip: "192.168.50.11",
		virtualbox__intnet: "net1"
		server.vm.hostname = "server"
#		config.ssh.username = 'vagrant'
# 		config.ssh.password = 'vagrant'
# 		config.ssh.keys_only = false
#		server.vm.provision "shell", path: "docker_install.sh"

	end
end