# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
config.vm.define "master" do |master|
  master.vm.hostname = "master"
  master.vm.network "private_network", ip: "192.168.10.10"
  master.vm.provision "shell", run: "always", path: "mysqlinstall.sh"
end
  
config.vm.define "slave" do |slave|
  slave.vm.hostname = "slave"
  slave.vm.network "private_network", ip: "192.168.10.20"
  slave.vm.provision "shell", run: "always", path: "mysqlinstall.sh"
end


end
