---
    - name: nginx start
      systemd: 
        name: nginx
        state: started

    - name: nginx restart
      systemd: 
        name: nginx
        state: restarted

    - name: postgresql start
      systemd: 
        name: postgresql 
        state: started

    - name: postgresql restart
      service: 
        name: postgresql 
        state: restarted      